import request from 'supertest';
import jwt from 'jsonwebtoken';
import { app } from '../app';
import { aiService } from '../services/ai';
import { env } from '../config/env';
import { Role } from '@prisma/client';

jest.mock('../services/ai', () => ({
  aiService: {
    generateArchitecture: jest.fn(),
  },
}));

describe('AI HTTP Routes', () => {
  const devToken = jwt.sign(
    { userId: 'usr-dev', email: 'dev@example.com', role: Role.DEVELOPER },
    env.JWT_SECRET,
  );

  const viewerToken = jwt.sign(
    { userId: 'usr-viewer', email: 'viewer@example.com', role: Role.VIEWER },
    env.JWT_SECRET,
  );

  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('POST /api/ai/generate', () => {
    it('should reject unauthenticated request with 401', async () => {
      const res = await request(app)
        .post('/api/ai/generate')
        .send({ prompt: 'Build a web server' });

      expect(res.status).toBe(401);
    });

    it('should reject VIEWER role with 403', async () => {
      const res = await request(app)
        .post('/api/ai/generate')
        .set('Authorization', `Bearer ${viewerToken}`)
        .send({ prompt: 'Build a web server' });

      expect(res.status).toBe(403);
    });

    it('should reject short prompt (< 3 chars) with 400', async () => {
      const res = await request(app)
        .post('/api/ai/generate')
        .set('Authorization', `Bearer ${devToken}`)
        .send({ prompt: 'hi' });

      expect(res.status).toBe(400);
    });

    it('should successfully return generated architecture for developer', async () => {
      (aiService.generateArchitecture as jest.Mock).mockResolvedValue({
        name: 'AI Generated Stack',
        description: 'Generated by Gemini',
        cloudProvider: 'AWS',
        rationale: 'Solid design',
        estimatedCostMonthlyUsd: 55,
        nodes: [{ id: 'n1', kind: 'compute', position: { x: 0, y: 0 }, data: { label: 'Web' } }],
        edges: [],
        terraformCode: '# code',
      });

      const res = await request(app)
        .post('/api/ai/generate')
        .set('Authorization', `Bearer ${devToken}`)
        .send({ prompt: 'Production AWS web app', cloudProvider: 'AWS' });

      expect(res.status).toBe(200);
      expect(res.body.architecture.name).toBe('AI Generated Stack');
      expect(aiService.generateArchitecture).toHaveBeenCalledWith({
        prompt: 'Production AWS web app',
        cloudProvider: 'AWS',
      });
    });
  });
});
